### ISSUE TITLE
Cannot read property 'element' of underfined

### ISSUE THREAD

**Issue by dsalodki** [1egoman/debundle#17]
I try command:
debundle -i inline.bundle.js -o dist/ -c debundle.config.js
StackTrace:
index.js:63

**Comment by dsalodki** [comment]
can not run on windows

**Comment by dsalodki** [comment]
debundle -i inline.bundle.js -o dist/ -c debundle.config.json
* Using default AST location for browserify...
* Reading bundle...
* Using auto-discovered browserify entry point...
/usr/local/lib/node_modules/debundle/src/index.js:63
  config.entryPoint = ast.body[0].expression.arguments[2].elements[0].value;
                                                          ^

TypeError: Cannot read property 'elements' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/debundle/src/index.js:63:59)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
root@dsalodki-Dell-System-XPS-L702X:/media/dsalodki/Data/exchange/wwwroot#

**Comment by 1egoman** [comment]
https://github.com/1egoman/debundle#dragon-here-be-dragons-dragon
